/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  296: {
    AuditAnchor: {
      address: "0x3e485CA75B4A49d186912Bb53C5BF1FEadF96d12",
      abi: [
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "user",
              type: "address",
            },
            {
              indexed: false,
              internalType: "enum AuditAnchor.ActionType",
              name: "actionType",
              type: "uint8",
            },
            {
              indexed: true,
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes32",
              name: "hcsRef",
              type: "bytes32",
            },
            {
              indexed: false,
              internalType: "uint64",
              name: "timestamp",
              type: "uint64",
            },
          ],
          name: "ActionAnchored",
          type: "event",
        },
        {
          inputs: [],
          name: "actionCount",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          name: "getAction",
          outputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "user",
                  type: "address",
                },
                {
                  internalType: "enum AuditAnchor.ActionType",
                  name: "actionType",
                  type: "uint8",
                },
                {
                  internalType: "address",
                  name: "asset",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "bytes32",
                  name: "hcsRef",
                  type: "bytes32",
                },
                {
                  internalType: "uint64",
                  name: "timestamp",
                  type: "uint64",
                },
              ],
              internalType: "struct AuditAnchor.ActionRecord",
              name: "",
              type: "tuple",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "user",
              type: "address",
            },
          ],
          name: "getUserActionIds",
          outputs: [
            {
              internalType: "uint256[]",
              name: "",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "enum AuditAnchor.ActionType",
              name: "actionType",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "hcsRef",
              type: "bytes32",
            },
          ],
          name: "recordAction",
          outputs: [
            {
              internalType: "uint256",
              name: "id",
              type: "uint256",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 41261508,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
