/**
 * This file is autogenerated by Scaffold-HBAR.
 * You should not edit it manually or your changes might be overwritten.
 * Run `yarn hardhat:deploy` to populate AuditAnchor addresses/ABIs.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {
  31337: {},
  296: {},
  295: {},
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
